### ISSUE TITLE
Repeated database calls

### ISSUE THREAD

**Issue by GaryJones** [Automattic/Cron-Control#191] opened 2020-05-29 12:19 UTC
A (VIP) client site is using Cron Control. When looking at their New Relic, after they had done some importing, it showed that `wp_a8c_cron_control_jobs` SELECT queries had a big impact. **It was called 64 times per transaction on average**. Looking specifically at one of them, it appears that the SELECT to that table was done 83 times for a single request - either the same, or a very similar query.

Looking into that more then, why does the cron table get read?

- Some of the cron calls are related to [async events for transition status changes](https://github.com/Automattic/vip-go-mu-plugins/blob/2d4ca5b98142eaf618ada901705f29507b4ff02d/async-publish-actions.php#L112) - as part of that, it schedules single events, and therefore reads from the cron table.
- When `publish_post` hook is called, it calls [`_publish_post_hook()` function](https://github.com/WordPress/WordPress/blob/a2accf4db7a4e6cf294bc6d34e99e4380625c6c2/wp-includes/post.php#L6813) which schedules a single event.
- Likewise, when the post status transitions, the [`_transition_post_status()` function](https://github.com/WordPress/WordPress/blob/a2accf4db7a4e6cf294bc6d34e99e4380625c6c2/wp-includes/post.php#L6747) is called, and that clears a scheduled event (which then eventually reads from the cron table).
- Jetpack and VaultPress also do things with cron and therefore end up querying the cron table as well.

So, what's the problem?

- All/many of the cron-related functions call the [`_get_cron_array()` WP core function](https://github.com/WordPress/WordPress/blob/47ed56f38ff85423c82642fa3a19b0948bf5b6a4/wp-includes/cron.php#L939), which calls `get_option( 'cron' );`.
- Cron Control [filters](https://github.com/Automattic/Cron-Control/blob/7956672085b76ab1362a687809dfb3c1c61d5a32/includes/class-events-store.php#L66) on `pre_get_cron`. Here's the [callback](https://github.com/Automattic/Cron-Control/blob/7956672085b76ab1362a687809dfb3c1c61d5a32/includes/class-events-store.php#L260).
- The callback is meant to use a static variable, and cache the results, but somehow the do-while loop which calls `get_jobs()` multiple times, is being run multiple times, from whatever stacktrace origin (see attached image).
- There are 20 of these four-call groups (i.e. the results of single calls to `Automattic\WP\Cron_Control\Events_Store::get_option`), each of which is taking 3.5% - 5.6% (averaging about 4%), and therefore taking up about ~80% of the request time. A 15-threaded importer (which is what the client was using at the time) hitting this would seem to me to be the likely cause of getting the 504s that they saw.
- Cron Control has [logic for splitting up values that are too large](https://github.com/Automattic/Cron-Control/blob/7956672085b76ab1362a687809dfb3c1c61d5a32/includes/class-events-store.php#L760-L799), so my thought is that **there's a bug in the logic here somewhere, either in saving, or accurately retrieving the cached option**, resulting the in do-while loop being called repeatedly.

Here's a partial view of the New Relic call trace:

<img width="1037" alt="Screenshot from New Relic call trace" src="https://user-images.githubusercontent.com/88371/83257569-8d94af80-a1ac-11ea-8f97-2f6c0939bc50.png">

**Comment by joshbetz** [comment] 2020-06-02 20:36
> The callback is meant to use a static variable, and cache the results, but somehow the do-while loop which calls get_jobs() multiple times, is being run multiple times, from whatever stacktrace origin (see attached image).

When I've looked into this in the past, I've come to the conclusion that this is actually working as expected. The problem is that any operation that modifies cron in any way (creating a job, running a job, removing a job) must set `is_option_cache_valid` to `false` and therefore busts the cache. Since the cron option is pretty volatile, it's almost impossible to cache it for very long.

To make matters worse, the common pattern of checking whether a job is scheduled before scheduling a job often runs on every page and therefore triggers an uncached cron lookup on every page.

@nickdaugherty has suggested using a Generator to query cron jobs as a potential solution. The array resulting from `get_option( 'cron' )` needs to contain all cron jobs or else core will think the missing jobs have been unscheduled. However, we don't always read all the jobs from that array. In those cases, we can actually save quite a few queries by progressively querying only the jobs we need.

**Comment by mjangda** [comment] 2020-06-04 06:12
I suspect most of these problems will go away once we stop relying on the `cron` option hack (i.e. #178 although that needs caching).

**Comment by WPprodigy** [comment] 2021-11-15 04:39
The above stack traces do appear to be "working as expected" per the current logic, but yeah this is definitely something that is solveable with the new filters.

Furthermore though, as far as imports go, this goes a long way for preventing the heavy cron usage (if it's not used): https://github.com/Automattic/vip-go-mu-plugins/pull/1999

So I think we are good to close this out, as the "new filters" enhancements are being tracked.

**Closed by WPprodigy** 2021-11-15 04:39 UTC
Labels: bug
